# scripts/build_adaptive_vocab.py
import json

# Curated high-frequency English words covering the full alphabet
# with deep coverage of the early sequence: E N I A R L T O S U D Y C G H P M K B W F Z V X Q J
COMMON_ENGLISH = [
    # E N I A R L (Early core)
    "air", "alien", "all", "an", "are", "area", "ear", "earn", "era", "ill", "in", "inn", "inner",
    "lane", "lean", "liar", "lie", "line", "linen", "nail", "near", "rail", "rain", "ran", "rare",
    "real", "rear", "rein", "aerial", "learn", "linear", "airline", "arena", "earl", "inane", "lair",
    "lain", "lira", "naira", "rani", "realer", "reline", "renal", "rile", "rarely", "linear", "alien",
    # + T
    "art", "at", "ate", "eat", "late", "let", "letter", "lit", "litter", "neat", "net", "nit", "rate",
    "rattle", "rent", "retail", "retain", "retire", "tale", "talent", "tall", "tart", "tear", "tenant",
    "tenet", "tent", "tile", "tilt", "tin", "tint", "tire", "title", "trail", "train", "trait", "treat",
    "tree", "alert", "alter", "later", "attend", "attain", "attrite", "entire", "initiate", "intent",
    "inter", "iterate", "latent", "little", "latter", "nettle", "orient", "reiterate", "relate", "reliant",
    "settle", "stare", "tartar", "tatter", "teeter", "tiller", "tine", "tinsel", "totter", "traitor",
    # + O
    "alone", "loan", "lion", "iron", "noon", "on", "one", "onto", "root", "rotten", "roll", "role",
    "loot", "tool", "notion", "nation", "into", "note", "ration", "riot", "rotate", "rotor", "tailor",
    "toil", "ton", "tone", "torn", "total", "toot", "ratio", "actor", "alteration", "atoll", "canoe",
    "color", "control", "cotton", "crane", "donor", "door", "floor", "honor", "horror", "indoor",
    "interior", "iron", "iteration", "lemon", "lesson", "lion", "loiter", "loot", "lotion", "motor",
    "noontime", "nor", "notation", "notate", "oar", "oil", "omit", "onion", "onto", "oral", "ration",
    "rationale", "rattle", "reactor", "roam", "roar", "roast", "robot", "rot", "rotate", "rotor", "tenor",
    "toot", "torment", "torn", "tornado", "tort", "trait", "trio", "trot",
    # + S
    "as", "asset", "assent", "east", "easier", "island", "is", "less", "lesson", "loss", "lose", "nest",
    "noise", "nose", "raise", "rise", "rose", "sail", "sale", "salt", "sea", "seal", "seat", "season",
    "see", "seen", "sense", "sensor", "series", "set", "settle", "sin", "sir", "sister", "site", "sole",
    "solo", "sonar", "son", "soon", "sore", "sort", "soul", "star", "stare", "start", "state", "station",
    "steal", "steel", "steer", "stir", "stone", "stool", "store", "strain", "stress", "toss", "assert",
    "assist", "astonish", "insist", "isolate", "lasso", "listen", "resist", "restart", "rooster", "sailor",
    "salsa", "sass", "satiate", "satin", "satire", "senator", "senior", "senseless", "sensible", "sister",
    "soar", "solar", "solicit", "solitary", "status", "stellar", "stilt", "strainer", "stroll", "suit",
    # + U
    "adult", "annual", "audit", "aunt", "auto", "autumn", "blur", "burn", "burst", "bus", "dust", "fault",
    "flute", "fruit", "glue", "guard", "guitar", "insult", "issue", "juice", "june", "lunar", "must",
    "natural", "neutral", "noun", "nurse", "nut", "out", "outline", "ruin", "rule", "run", "rust", "rural",
    "sauce", "sauna", "slur", "snout", "soul", "sour", "suit", "suite", "sun", "sure", "tour", "true",
    "trust", "truth", "tune", "tunnel", "turn", "unit", "unite", "until", "usual", "utter",
    # + D
    "add", "ahead", "aid", "and", "around", "bad", "bed", "bend", "bind", "bird", "blade", "blend", "blind",
    "blood", "board", "bold", "bond", "bound", "bread", "broad", "build", "cloud", "cold", "could", "crowd",
    "dad", "dance", "dare", "dark", "date", "dead", "deal", "dear", "death", "decide", "deep", "deer", "den",
    "desk", "dial", "diet", "dine", "dirt", "dish", "dive", "do", "doctor", "dog", "doll", "door", "dot",
    "doubt", "down", "drain", "draw", "dream", "dress", "drift", "drill", "drink", "drive", "drop", "drum",
    "dry", "due", "dull", "dust", "duty", "end", "feed", "find", "flood", "fold", "food", "friend", "glad",
    "gold", "good", "grade", "grand", "guide", "hand", "hard", "head", "hide", "hold", "island", "land",
    "lead", "load", "loud", "mind", "need", "odd", "old", "order", "proud", "radio", "read", "red", "ride",
    "road", "round", "sad", "sand", "seed", "send", "side", "slide", "solid", "sound", "stand", "trade",
    "under", "wide", "wind", "wood", "word", "world", "yard",
    # + Y
    "any", "away", "bay", "boy", "busy", "buy", "by", "city", "clay", "copy", "cry", "daily", "day", "deny",
    "dry", "duty", "early", "easy", "empty", "enjoy", "entry", "every", "eye", "fly", "gray", "guy", "heavy",
    "lady", "lay", "lazy", "may", "many", "maybe", "my", "play", "pray", "ready", "rely", "reply", "say",
    "sky", "stay", "story", "study", "they", "toy", "try", "ugly", "very", "way", "why", "year", "yes", "yet",
    "yield", "you", "young", "your",
    # + C
    "act", "action", "actor", "basic", "beach", "block", "brick", "call", "calm", "camp", "can", "car", "card",
    "care", "case", "cat", "catch", "cause", "cell", "center", "chain", "chair", "chance", "change", "chart",
    "chase", "cheap", "check", "cheek", "cheer", "chest", "chief", "child", "chin", "choice", "choose", "church",
    "circle", "city", "claim", "clap", "class", "clean", "clear", "climb", "clock", "close", "cloth", "cloud",
    "club", "coach", "coast", "coat", "coin", "cold", "color", "come", "cook", "cool", "copy", "corn", "corner",
    "cost", "count", "court", "cover", "crack", "crash", "cream", "cross", "crowd", "cry", "cup", "cure", "curl",
    # + G
    "age", "ago", "agree", "among", "angel", "anger", "angry", "argue", "bag", "beg", "begin", "big", "bring",
    "bug", "cage", "dig", "dog", "dragon", "drug", "eager", "egg", "eight", "energy", "engine", "fig", "flag",
    "fog", "frog", "gain", "game", "gap", "gas", "gate", "gather", "gear", "giant", "gift", "girl", "give", "glad",
    "glass", "glow", "glue", "go", "goal", "goat", "gold", "gone", "good", "grab", "grace", "grade", "grain", "grand",
    "grape", "grass", "gray", "great", "green", "greet", "grey", "grief", "grin", "grip", "ground", "group", "grow",
    "guard", "guess", "guest", "guide", "guilt", "guitar", "gun", "guy", "hang", "huge", "hunger", "hungry", "judge",
    "king", "large", "leg", "light", "log", "long", "lung", "magic", "night", "page", "pig", "plug", "range", "ring",
    "sing", "song", "spring", "stage", "string", "strong", "sugar", "target", "tiger", "wing",
    # + H
    "ache", "ahead", "ash", "bath", "beach", "birth", "both", "branch", "breath", "bush", "cash", "catch", "chain",
    "chair", "chance", "change", "chart", "chase", "cheap", "check", "cheek", "cheer", "chest", "chief", "child",
    "chin", "choice", "choose", "church", "cloth", "coach", "crash", "dish", "earth", "faith", "fish", "flash", "flesh",
    "forth", "fresh", "ghost", "half", "hall", "hammer", "hand", "hang", "happen", "happy", "hard", "harm", "hat",
    "hate", "have", "he", "head", "heal", "health", "heap", "hear", "heart", "heat", "heavy", "heel", "height", "hello",
    "help", "her", "herd", "here", "hero", "hide", "high", "hill", "him", "hint", "hip", "hire", "his", "hit", "hold",
    "hole", "holy", "home", "honest", "honey", "honor", "hook", "hope", "horn", "horse", "host", "hot", "hotel", "hour",
    "house", "how", "huge", "human", "hunt", "hurry", "hurt", "hush", "hut", "inch", "laugh", "light", "lunch", "match",
    "math", "month", "mouth", "much", "north", "path", "peach", "phase", "photo", "pitch", "push", "reach", "rich",
    "rough", "rush", "search", "shadow", "shake", "shall", "shame", "shape", "share", "sharp", "she", "sheet", "shelf",
    "shell", "shine", "ship", "shirt", "shock", "shoe", "shoot", "shop", "shore", "short", "shot", "should", "shout",
    "show", "shut", "sight", "smith", "south", "speech", "such", "teach", "thank", "that", "the", "their", "them",
    "then", "there", "these", "they", "thick", "thief", "thin", "thing", "think", "third", "this", "thorn", "though",
    "thread", "three", "throat", "through", "throw", "thumb", "tooth", "touch", "tough", "truth", "wash", "watch",
    "wealth", "wheat", "wheel", "when", "where", "which", "while", "white", "who", "whole", "whom", "whose", "why",
    "width", "wish", "with", "worth", "youth",
    # + P
    "apple", "april", "apron", "camp", "cap", "cape", "captain", "carpet", "champion", "cheap", "chip", "chop", "clap",
    "clip", "company", "compass", "cope", "copper", "copy", "crop", "cup", "deep", "depend", "depth", "dip", "drop",
    "dump", "empty", "escape", "example", "expert", "explore", "grape", "grasp", "grip", "group", "heap", "help", "hip",
    "hope", "hop", "hospital", "impact", "impulse", "input", "jump", "keep", "lamp", "lap", "leap", "limp", "lip",
    "loop", "lump", "map", "mop", "nap", "open", "opera", "pace", "pack", "page", "pain", "paint", "pair", "pale",
    "palm", "pan", "panel", "panic", "paper", "parade", "parcel", "pardon", "parent", "park", "part", "party", "pass",
    "past", "paste", "path", "patrol", "pause", "pay", "pea", "peace", "peach", "peak", "pear", "pearl", "pen",
    "pencil", "people", "pepper", "per", "period", "person", "pet", "phase", "phone", "photo", "phrase", "pick",
    "picture", "pie", "piece", "pig", "pile", "pilot", "pin", "pinch", "pink", "pipe", "pitch", "place", "plain",
    "plan", "plane", "planet", "plant", "plate", "play", "plead", "please", "pledge", "plenty", "plot", "plow", "plug",
    "plum", "plus", "pocket", "poem", "poet", "point", "poison", "pole", "police", "policy", "polish", "polite", "pond",
    "pool", "poor", "pop", "pork", "port", "pose", "post", "pot", "potato", "pound", "pour", "power", "praise", "pray",
    "press", "pretty", "price", "pride", "priest", "prime", "prince", "print", "prior", "prison", "prize", "probe",
    "profit", "prompt", "proof", "proper", "proud", "prove", "provide", "public", "pull", "pump", "punch", "pupil",
    "puppy", "pure", "purple", "purse", "push", "puzzle", "rapid", "reap", "repeat", "reply", "report", "rope", "ripe",
    "sample", "scope", "scrap", "scrape", "script", "shape", "sharp", "sheep", "sheet", "ship", "shop", "simple",
    "sleep", "slip", "slope", "snap", "soap", "soup", "space", "spark", "speak", "speed", "spell", "spend", "spill",
    "spin", "spirit", "spite", "split", "spoil", "spoon", "sport", "spot", "spread", "spring", "spur", "spy", "stamp",
    "step", "stop", "strap", "strip", "stripe", "stupid", "super", "supper", "supply", "sweep", "tap", "tape", "temple",
    "tip", "top", "topic", "trap", "trip", "troop", "type", "up", "upon", "upper", "upset", "wrap",
    # + M
    "aim", "album", "almost", "among", "amount", "animal", "arm", "army", "atom", "autumn", "beam", "blame", "bloom",
    "boom", "bottom", "broom", "calm", "camera", "camp", "claim", "climb", "come", "cream", "crime", "custom", "dam",
    "damage", "damp", "dim", "dome", "dream", "drum", "dump", "element", "empire", "empty", "enemy", "fame", "farm",
    "film", "flame", "foam", "form", "frame", "from", "game", "germ", "gloom", "gram", "gum", "hammer", "harm", "helmet",
    "home", "human", "humor", "item", "jam", "jump", "lamp", "lemon", "lime", "limit", "limb", "lump", "mad", "magic",
    "maid", "mail", "main", "major", "make", "male", "man", "manage", "many", "map", "march", "mark", "market", "mask",
    "mass", "mast", "master", "match", "mate", "matter", "may", "maybe", "mayor", "me", "meal", "mean", "meat", "medal",
    "media", "medium", "meet", "melon", "melt", "member", "memory", "men", "mend", "mental", "menu", "mercy", "mere",
    "merge", "merit", "merry", "mesh", "mess", "metal", "meter", "method", "middle", "might", "mild", "mile", "milk",
    "mill", "mind", "mine", "minor", "mint", "minute", "mirror", "miss", "mist", "mix", "moan", "mob", "mock", "mode",
    "model", "modest", "moist", "mold", "mole", "molt", "moment", "monk", "month", "mood", "moon", "moor", "mop", "moral",
    "more", "morn", "mosaic", "most", "moth", "mother", "motion", "motor", "motto", "mount", "mouse", "mouth", "move",
    "movie", "much", "mud", "muff", "mule", "multi", "mumble", "muscle", "museum", "music", "must", "mute", "mutter",
    "mutual", "muzzle", "my", "myself", "name", "norm", "normal", "poem", "problem", "program", "promise", "room",
    "same", "scam", "scream", "seem", "shame", "slim", "smart", "smell", "smile", "smoke", "smooth", "some", "spam",
    "spasm", "stadium", "stamp", "steam", "stem", "storm", "stream", "sum", "summer", "swam", "swim", "system", "team",
    "term", "them", "time", "tomb", "warm",
    # + K
    "ask", "awake", "bake", "bank", "bark", "beak", "blank", "blink", "block", "book", "break", "brick", "brook", "cake",
    "chalk", "check", "cheek", "clerk", "click", "cloak", "clock", "cook", "cork", "crank", "creak", "creek", "crook",
    "dark", "desk", "drink", "duck", "dusk", "flake", "flock", "folk", "fork", "frank", "hawk", "hook", "ink", "joke",
    "keen", "keep", "kettle", "key", "kick", "kid", "kill", "kin", "kind", "king", "kiss", "kite", "kitten", "knee",
    "kneel", "knife", "knit", "knob", "knock", "knot", "know", "lake", "leak", "like", "link", "lock", "look", "luck",
    "make", "mark", "market", "mask", "milk", "monk", "naked", "neck", "oak", "pack", "park", "peak", "peck", "pick",
    "pink", "pork", "prank", "quick", "rake", "rank", "risk", "rock", "sack", "sake", "seek", "shake", "shark", "shock",
    "sick", "silk", "sink", "skate", "skill", "skin", "skirt", "skull", "sky", "smoke", "snake", "sneak", "sock", "soak",
    "spark", "speak", "spoke", "stake", "stalk", "steak", "stick", "stock", "stroke", "struck", "sunk", "take", "talk",
    "tank", "task", "thick", "think", "track", "trick", "trunk", "wake", "walk", "week", "work",
    # + B
    "baby", "back", "bacon", "bad", "bag", "bake", "ball", "band", "bang", "bank", "bar", "bare", "bark", "barn",
    "base", "basic", "basin", "basket", "bat", "bath", "battle", "bay", "be", "beach", "bead", "beak", "beam", "bean",
    "bear", "beard", "beast", "beat", "beauty", "bed", "bee", "beef", "beer", "beg", "begin", "bell", "belt", "bench",
    "bend", "berry", "best", "bet", "better", "bid", "big", "bike", "bill", "bind", "bird", "birth", "bit", "bite",
    "bitter", "black", "blade", "blame", "blank", "blast", "blaze", "bleed", "blend", "bless", "blind", "blink", "bliss",
    "block", "blood", "bloom", "blot", "blouse", "blow", "blue", "blur", "blush", "boar", "board", "boast", "boat", "body",
    "boil", "bold", "bolt", "bomb", "bond", "bone", "book", "boom", "boot", "booth", "border", "bore", "born", "borrow",
    "boss", "both", "bother", "bottle", "bottom", "bough", "bounce", "bound", "bow", "bowl", "box", "boy", "brace", "brag",
    "braid", "brain", "brake", "branch", "brand", "brass", "brave", "bread", "break", "breast", "breath", "breeze", "brick",
    "bride", "bridge", "brief", "bright", "brim", "bring", "brisk", "broad", "broil", "broke", "brook", "broom", "broth",
    "brown", "browse", "brush", "bubble", "buck", "bucket", "bud", "buff", "bug", "build", "bulb", "bulk", "bull", "bullet",
    "bump", "bunch", "bundle", "bunk", "burden", "burn", "burst", "bury", "bus", "bush", "busy", "but", "butter", "button",
    "buy", "buzz", "by", "cabin", "cable", "crab", "club", "debt", "doubt", "elbow", "fiber", "globe", "grab", "habit",
    "harbor", "herb", "hobby", "labor", "lamb", "limb", "lobby", "marble", "member", "mob", "noble", "number", "obey",
    "orbit", "public", "rabbit", "ribbon", "robin", "robot", "rubber", "ruby", "sob", "sober", "subway", "table", "timber",
    "tribe", "tube", "tumble", "urban", "web",
    # + W
    "awake", "aware", "away", "claw", "cow", "crow", "dawn", "dew", "down", "draw", "drew", "flaw", "flow", "glow",
    "grow", "hawk", "jaw", "know", "lawn", "law", "low", "mow", "new", "now", "owl", "raw", "row", "saw", "sew",
    "shadow", "show", "slow", "snow", "sow", "straw", "swallow", "swan", "swarm", "sweat", "sweep", "sweet", "swell",
    "swift", "swim", "swing", "sword", "tow", "town", "view", "vow", "wade", "wage", "wagon", "waist", "wait", "wake",
    "walk", "wall", "walnut", "wander", "want", "war", "ward", "warm", "warn", "warp", "wash", "wasp", "waste", "watch",
    "water", "wave", "wax", "way", "we", "weak", "wealth", "wear", "weave", "web", "wed", "weed", "week", "weep", "weigh",
    "weight", "well", "west", "wet", "whale", "what", "wheat", "wheel", "when", "where", "which", "while", "whip", "whirl",
    "white", "who", "whole", "whom", "whose", "why", "wicked", "wide", "widow", "width", "wife", "wild", "will", "willow",
    "win", "wind", "window", "wine", "wing", "wink", "winter", "wipe", "wire", "wise", "wish", "wit", "witch", "with",
    "wobble", "wolf", "woman", "womb", "women", "won", "wood", "wool", "word", "work", "world", "worm", "worry", "worse",
    "worst", "worth", "wound", "wrap", "wreck", "wrist", "write", "wrong",
    # + F
    "affair", "affect", "afford", "after", "brief", "cafe", "calf", "chief", "cliff", "coffee", "craft", "deaf", "defeat",
    "defect", "draft", "drift", "dwarf", "effort", "elf", "fade", "fail", "faint", "fair", "faith", "fall", "false",
    "fame", "family", "famous", "fan", "fancy", "far", "farm", "farmer", "fast", "fat", "fatal", "fate", "father", "fault",
    "favor", "fear", "feast", "feat", "feather", "fee", "feed", "feel", "feet", "fellow", "female", "fence", "fern",
    "ferry", "fetch", "fever", "few", "fiber", "field", "fierce", "fifth", "fifty", "fig", "fight", "figure", "file",
    "fill", "film", "filter", "filth", "final", "find", "fine", "finger", "finish", "fir", "fire", "firm", "first",
    "fish", "fist", "fit", "five", "fix", "flag", "flair", "flake", "flame", "flap", "flare", "flash", "flask", "flat",
    "flavor", "flaw", "flee", "fleet", "flesh", "flight", "flock", "flood", "floor", "flour", "flow", "flower", "flute",
    "fly", "foam", "focus", "fog", "foil", "fold", "folk", "follow", "folly", "fond", "food", "fool", "foot", "for",
    "force", "ford", "forest", "forge", "forget", "fork", "form", "fort", "forth", "fortune", "forty", "foster", "foul",
    "found", "fountain", "four", "fox", "fraction", "frame", "frank", "fraud", "free", "freedom", "freeze", "freight",
    "french", "fresh", "fret", "friction", "friday", "friend", "frisk", "frog", "from", "front", "frost", "froth", "frown",
    "frozen", "fruit", "fry", "fuel", "full", "fumble", "fume", "fun", "fund", "funny", "fur", "furious", "furnace",
    "furnish", "furry", "fury", "fuse", "future", "fuzz", "grief", "half", "leaf", "life", "lift", "loaf", "off",
    "offer", "office", "often", "profit", "proof", "refuse", "relief", "roof", "safe", "scarf", "shift", "soft", "staff",
    "stuff", "tariff", "thief", "wolf",
    # + Z
    "blaze", "breeze", "bronze", "buzz", "citizen", "craze", "crazy", "daze", "dazzle", "doze", "dozen", "freeze", "frenzy",
    "froze", "frozen", "fuzz", "fuzzy", "gaze", "graze", "grizzly", "hazard", "haze", "hazel", "horizon", "lazy", "lizard",
    "maze", "muzzle", "nozzle", "ooze", "organize", "ozone", "plaza", "prize", "puzzle", "quartz", "quiz", "razor",
    "realize", "recognize", "seize", "sneeze", "snoze", "squeeze", "stanza", "topaz", "trapeze", "wizard", "zeal", "zebra",
    "zenith", "zero", "zest", "zigzag", "zinc", "zip", "zipper", "zone", "zoom",
    # + V
    "above", "active", "alive", "arrive", "avenue", "avoid", "brave", "cave", "clever", "clove", "clover", "cove", "cover",
    "crave", "curve", "dove", "drive", "driver", "drove", "event", "ever", "every", "evident", "evil", "evolve", "fever",
    "five", "flavor", "give", "giver", "glove", "grave", "gravel", "gravity", "grove", "harvest", "have", "haven", "heavy",
    "hive", "hover", "invent", "invest", "invite", "irony", "leave", "level", "lever", "live", "liver", "love", "lover",
    "move", "mover", "native", "navy", "nerve", "never", "novel", "olive", "oval", "oven", "over", "pave", "pavement",
    "privy", "prove", "proven", "provide", "ravel", "rave", "remove", "revive", "river", "save", "saver", "serve", "server",
    "seven", "sever", "several", "shave", "shiver", "shove", "silver", "slave", "sleeve", "solve", "starve", "stove",
    "travel", "valve", "vapor", "vast", "vault", "veal", "veer", "veil", "vein", "velvet", "venture", "verb", "verdict",
    "verge", "verify", "verse", "version", "very", "vessel", "vest", "veteran", "via", "vibrate", "vicar", "vice", "victim",
    "victor", "victory", "video", "view", "viewer", "vigil", "vigor", "vile", "villa", "village", "vine", "vintage",
    "vinyl", "viola", "violet", "violin", "viper", "virgin", "virtue", "virus", "visa", "visage", "visit", "visitor",
    "visor", "vista", "visual", "vital", "vitamin", "vivid", "vixen", "vocal", "vodka", "vogue", "voice", "void", "volt",
    "volume", "vomit", "vote", "voter", "votive", "vouch", "vow", "vowel", "voyage", "wave", "waver", "weave",
    # + X
    "anxious", "apex", "appendix", "approx", "axes", "axis", "box", "boxer", "climax", "coax", "complex", "convex", "crux",
    "detox", "exact", "exalt", "examine", "example", "exceed", "excel", "except", "excess", "exchange", "excite", "exclude",
    "excuse", "execute", "exempt", "exercise", "exert", "exhaust", "exhibit", "exile", "exist", "exit", "exotic", "expand",
    "expect", "expel", "expense", "expert", "expire", "explain", "explode", "exploit", "explore", "export", "expose",
    "express", "extend", "extent", "extra", "extreme", "fix", "fixed", "fixture", "flax", "flex", "flexible", "fox",
    "galaxy", "index", "luxury", "matrix", "max", "maximum", "mix", "mixer", "mixture", "next", "ox", "oxen", "oxygen",
    "pixel", "prefix", "prospect", "proxy", "reflex", "relax", "six", "sixteen", "sixth", "sixty", "suffix", "syntax",
    "tax", "taxi", "text", "toxic", "toxin", "wax",
    # + Q
    "adequate", "antique", "aqua", "aquatic", "banquet", "conquer", "equal", "equality", "equation", "equator", "equity",
    "equip", "liquor", "liquid", "opaque", "plaque", "quack", "quad", "quail", "quaint", "quake", "qualify", "quality",
    "qualm", "quantum", "quarry", "quart", "quarter", "quartet", "quartz", "quasar", "quay", "queen", "queer", "quell",
    "quench", "query", "quest", "question", "queue", "quick", "quicken", "quiet", "quilt", "quip", "quirk", "quit",
    "quite", "quiver", "quiz", "quota", "quote", "require", "request", "sequence", "squad", "square", "squash", "squat",
    "squeak", "squeeze", "squint", "squirrel", "squirt", "torque", "tranquil", "unique",
    # + J
    "adjust", "adjoin", "adjourn", "badge", "banjo", "cajole", "deejay", "disjoin", "enjoy", "fudge", "hedge", "hijack",
    "injury", "jail", "jam", "jar", "jargon", "jaw", "jay", "jazz", "jealous", "jeep", "jeer", "jelly", "jerk", "jersey",
    "jest", "jet", "jewel", "jig", "jingle", "job", "jockey", "jocund", "jog", "join", "joint", "joke", "jolly", "jolt",
    "journal", "journey", "joust", "jovial", "joy", "joyful", "judge", "judgment", "jug", "juggle", "juice", "juicy",
    "juke", "jumble", "jumbo", "jump", "jumper", "jumpy", "junction", "june", "jungle", "junior", "junk", "junta",
    "juror", "jury", "just", "justice", "justify", "jut", "jute", "juvenile", "major", "object", "project", "reject",
    "rejoice", "subject"
]

# Deduplicate and sort
words = sorted(list(set([w.lower().strip() for w in COMMON_ENGLISH if len(w) >= 2 and w.isalpha()])))
print(f"Total curated English words: {len(words)}")

# Write to data/adaptive-vocab.js
with open("data/adaptive-vocab.js", "w", encoding="utf-8") as f:
    f.write("/* PK Khmer Type — Curated Offline Adaptive Vocabulary */\n")
    f.write("(function(global){\n")
    f.write("  'use strict';\n\n")
    f.write("  const ENGLISH_ADAPTIVE_WORDS = " + json.dumps(words, ensure_ascii=False) + ";\n\n")
    f.write("  if(typeof module !== 'undefined' && module.exports){\n")
    f.write("    module.exports = { ENGLISH_ADAPTIVE_WORDS };\n")
    f.write("  }\n")
    f.write("  global.ENGLISH_ADAPTIVE_WORDS = ENGLISH_ADAPTIVE_WORDS;\n")
    f.write("})(typeof window !== 'undefined' ? window : global);\n")

print("Created data/adaptive-vocab.js successfully!")

