#!/usr/bin/env node
/**
 * Reads VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY from process.env, .env.local, or .env
 * and writes a runtime browser environment shim to js/supabase-env.js (gitignored).
 * Never writes service_role or secret keys.
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");

function parseEnvFile(filePath) {
  const result = {};
  if (!fs.existsSync(filePath)) return result;
  const content = fs.readFileSync(filePath, "utf8");
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const eqIdx = line.indexOf("=");
    if (eqIdx === -1) continue;
    const key = line.slice(0, eqIdx).trim();
    let val = line.slice(eqIdx + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    result[key] = val;
  }
  return result;
}

const dotEnv = parseEnvFile(path.join(ROOT, ".env"));
const dotEnvLocal = parseEnvFile(path.join(ROOT, ".env.local"));

const supabaseUrl = (
  process.env.VITE_SUPABASE_URL ||
  dotEnvLocal.VITE_SUPABASE_URL ||
  dotEnv.VITE_SUPABASE_URL ||
  ""
).trim();

const supabaseAnonKey = (
  process.env.VITE_SUPABASE_ANON_KEY ||
  dotEnvLocal.VITE_SUPABASE_ANON_KEY ||
  dotEnv.VITE_SUPABASE_ANON_KEY ||
  ""
).trim();

if (supabaseAnonKey.startsWith("sb_secret_") || /service_role/i.test(supabaseAnonKey)) {
  console.error("[PK Cloud Sync] SECURITY ERROR: Refusing to bundle a secret or service_role key into VITE_SUPABASE_ANON_KEY.");
  process.exit(1);
}

const outPath = path.join(ROOT, "js", "supabase-env.js");
const banner = [
  "/* Auto-generated by scripts/generate_supabase_config.js — DO NOT COMMIT SECRETS */",
  "window.__PK_VITE_ENV__ = Object.assign({}, window.__PK_VITE_ENV__ || {}, {",
  "  VITE_SUPABASE_URL: " + JSON.stringify(supabaseUrl) + ",",
  "  VITE_SUPABASE_ANON_KEY: " + JSON.stringify(supabaseAnonKey),
  "});",
  ""
].join("\n");

fs.writeFileSync(outPath, banner, "utf8");
console.log(
  "[PK Cloud Sync] Generated js/supabase-env.js (" +
    (supabaseUrl && supabaseAnonKey ? "Supabase configured" : "No credentials set — setup notice will be shown when cloud auth is opened") +
    ")"
);
