import { useEffect, useState } from 'react';
import keyboardData from '../data/keyboard.json';
import englishLessons from '../data/curriculum/english/lessons.json'; import englishExercises from '../data/curriculum/english/exercises.json';
import nidaLessons from '../data/curriculum/nida/lessons.json'; import nidaExercises from '../data/curriculum/nida/exercises.json';
import standardLessons from '../data/curriculum/standard/lessons.json'; import standardExercises from '../data/curriculum/standard/exercises.json';
import { Keyboard } from './components/keyboard/Keyboard.jsx'; import { LessonList } from './components/lessons/LessonList.jsx'; import { TypingArea } from './components/typing/TypingArea.jsx'; import { AdaptivePractice } from './components/adaptive/AdaptivePractice.jsx'; import { Race } from './components/race/Race.jsx'; import { Statistics } from './components/statistics/Statistics.jsx'; import { Settings } from './components/settings/Settings.jsx';
import { useProgress } from './hooks/useProgress.js'; import { useTypingSession } from './hooks/useTypingSession.js'; import { readSettings, saveSettings } from './storage/settingsStorage.js';
const courses = { english: { lessons: englishLessons.lessons, exercises: englishExercises.exercises }, nida: { lessons: nidaLessons.lessons, exercises: nidaExercises.exercises }, standard: { lessons: standardLessons.lessons, exercises: standardExercises.exercises } };
export default function App() {
  const [settings, setSettings] = useState(readSettings); const [layout, setLayout] = useState(settings.layout || 'standard'); const [screen, setScreen] = useState('lessons'); const [lessonIndex, setLessonIndex] = useState(0); const [modal, setModal] = useState(null); const { progress, recordAttempt, resetCourse } = useProgress(); const course = courses[layout]; const lesson = course.lessons[lessonIndex] || course.lessons[0]; const target = course.exercises[lesson?.exerciseRefs?.[0]]?.content || ''; const session = useTypingSession({ target, layout, enabled: screen === 'lessons' });
  useEffect(() => setLessonIndex(0), [layout]); useEffect(() => saveSettings({ ...settings, layout }), [settings, layout]); useEffect(() => { if (session.completed && lesson) recordAttempt(layout, lesson, session.summary); }, [session.completed]);
  const selectLesson = index => { setLessonIndex(index); setScreen('lessons'); session.reset(); };
  return <div className="min-h-screen bg-slate-950 text-slate-100"><header className="sticky top-0 z-20 border-b border-slate-800 bg-slate-950/95 px-4 py-3 backdrop-blur"><div className="mx-auto flex max-w-7xl flex-wrap items-center gap-3"><div className="mr-auto"><h1 className="text-lg font-bold text-amber-300">PK Khmer Type</h1><p className="text-xs text-slate-400">Practice with purpose</p></div>{Object.entries(keyboardData.LAYOUTS).map(([id, item]) => <button key={id} onClick={() => { setLayout(id); setScreen('lessons'); }} className={`rounded-md px-3 py-2 text-sm ${layout === id ? 'bg-amber-400 text-slate-950' : 'bg-slate-800 hover:bg-slate-700'}`}>{item.label}</button>)}<button onClick={() => setModal('statistics')} className="rounded-md bg-slate-800 px-3 py-2 text-sm">Statistics</button><button onClick={() => setModal('settings')} className="rounded-md bg-slate-800 px-3 py-2 text-sm">Settings</button></div></header><main className="mx-auto grid max-w-7xl gap-6 p-4 lg:grid-cols-[19rem_1fr]"><aside className="space-y-4"><nav className="grid grid-cols-3 gap-2 lg:grid-cols-1">{['lessons', 'adaptive', 'race'].map(item => <button key={item} onClick={() => setScreen(item)} className={`rounded-md px-3 py-2 text-left text-sm capitalize ${screen === item ? 'bg-cyan-500 text-slate-950' : 'bg-slate-800 hover:bg-slate-700'}`}>{item === 'adaptive' ? 'Adaptive Practice' : item}</button>)}</nav><LessonList lessons={course.lessons} completed={progress.courses?.[layout]?.lessons || {}} selected={lessonIndex} onSelect={selectLesson} /></aside><section className="min-w-0 space-y-5">{screen === 'lessons' && <><TypingArea lesson={lesson} target={target} session={session} onPrevious={() => selectLesson(Math.max(0, lessonIndex - 1))} onRetry={session.reset} onNext={() => selectLesson(Math.min(course.lessons.length - 1, lessonIndex + 1))} /><Keyboard layout={keyboardData.LAYOUTS[layout]} pressedCode={session.pressedCode} expected={session.expected} /></>}{screen === 'adaptive' && <AdaptivePractice layout={layout} keyboard={keyboardData.LAYOUTS[layout]} onExit={() => setScreen('lessons')} />}{screen === 'race' && <Race layout={layout} onExit={() => setScreen('lessons')} />}</section></main>{modal === 'statistics' && <Statistics progress={progress} onClose={() => setModal(null)} />}{modal === 'settings' && <Settings settings={settings} onChange={setSettings} onReset={() => resetCourse(layout)} onClose={() => setModal(null)} />}</div>;
}
